config/routes.rb
Rails.application.routes.draw do

  match 'start', to: 'pages#start', via: [:get, :post]

  post 'image', to: 'pages#image', as: :image

  root 'pages#start'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def start

    require 'scrambler'

    phrase = params[:phrase]
    if phrase
      contents = phrase == '' ? "Come on, you got nothing? 🤨" : phrase
      @results = Scrambler.process(contents)
    end

    respond_to do |format|
      format.html
      format.js
    end
  end


  def image
    kit = IMGKit.new("<html><head></head><body>hello</body></html>", width: 480, height: 800, quality: 100)
    respond_to do |format|
      format.png do
        send_data(kit.to_jpg, type: "image/png", disposition: 'inline')
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-129396772-1"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-129396772-1');
  </script>

  <%= render 'application/favicon' %>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Fun app to jumble words in any phrase!">
  <meta name="keywords" content="gibberish, jumble, words">
  <meta name="author" content="">

  <title>Jbbrsh</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Bootstrap core CSS -->
  <%= stylesheet_link_tag 'application',
                          "https://fonts.googleapis.com/css?family=Gloria+Hallelujah|Muli",
                          media:                  'all'
  %>

  <!-- Bootstrap core JavaScript -->
  <%= javascript_include_tag "application" %>
</head>

<body>

<!-- Page Content -->
<%= yield %>

<footer>
  <div class="row text-center">
    <div class="col small instructions">
      Ceeratd by <%= link_to '@xiankt', 'https://twitter.com/xiankt' %>
    </div>
  </div>
</footer>

</body>

</html>

app/views/pages/_copy_button.html.erb
<% if results %>
<div class="form-group row">
  <button style="margin-left:15px;"
          class=".button"
          data-clipboard-text="<%= results %> ** Created using jbbrsh.com "
          id="copy-btn">
    copy
  </button>
</div>
<% end %>

app/views/pages/_results.html.erb
<% if results %>
  <%= results %>
<% end %>



<%#= form_tag image_path(format: :png) do %>
<%#= submit_tag "Download Image" %>
<%# end %>

app/views/pages/image.png.erb
<!DOCTYPE html>
<html>
<head>
  <title>Image</title>
  <style type='text/css'>
    html {
    . . .
    }
  </style>
</head>
<body>
<p>hello</p>
</body>
</html>

app/views/pages/start.html.erb
<div class="main-content container">

  <section id="banner">
    <div class="row text-center">
      <div class="col">
        <p id="banner-header">Jbbrsh</p>
        <p id="banner-subheader"> "ji-be-rish" </p>
      </div>
    </div>
  </section>

  <section id="intro">
    <div class="row">
      <div class="col">
        <p class="instructions">

          Not eervynoe can raed tihs ... Rbibush!
          Of csoure tehy can. Can tehy wirte it thugoh?
          Wtih Jbbrsh YOU can :)

          <br>
        </p>
      </div>
    </div>
  </section>

  <section id="main">
    <div class="row">
      <div class="col-6">
        <div id="form">
          <%= form_tag start_path, remote: true do %>

            <div class="form-group">
              <%= text_area_tag :phrase,
                                '',
                                placeholder: 'Go ahead, give it a spin',
                                class: 'form-control',
                                rows:  10
              %>

            </div>

            <div class="form-group" >
              <%= submit_tag "jbbrsh it!", class: 'mb-2' %>
            </div>

          <% end %>
        </div>
      </div>

      <div class="col-6">
        <div id="results">
          <%= render partial: 'pages/results',
                     locals:  {
                         results: nil
                     }
          %>
        </div>
        <div id="action-buttons">
          <%= render partial: 'pages/copy_button',
                     locals:  {
                         results: nil
                     }
          %>
        </div>
      </div>

    </div>
  </section>

  <section id="info">
    <div class="row text-center">
      <p class="col instructions">
        <i> <strong>Pro tip 1:</strong> sunrorud any wrod you dnot wnat jbbrshed wtih an * e.g. *Jenny* </i>
      </p>
    </div>
  </section>

</div> <!--end main-content-->

app/views/pages/start.js.erb
$('#results').html(
    function () {
        return (
            '<%= j render partial: 'pages/results',
                          locals: {
                            results: @results,
                          }
                          %>'
        );
    }
);


$('#action-buttons').html(
    function () {
        return (
            '<%= j render partial: 'pages/copy_button',
                          locals: {
                            results: @results,
                          }
                          %>'
        );
    }
);


initCopyText();